Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/SingleLineBlockParams:
  Enabled: false

Rails:
  Enabled: true
Rails/FilePath:
  Enabled: false
Rails/Output:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - client/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - Guardfile
